### PR TITLE
add faucet button to docs site

### PR DESCRIPTION
**Pull request by eshaben**
Add faucet button to the docs site in the top navigation next to the connect metamask button. Uses a faucet icon instead of text. LMK what ya think!

### CODE REVIEW

**Comment by eshaben** [comment]
Screenshot 2023-05-10 at 11 12 07 PM

**Comment by albertov19** [comment]
@eshaben I added the `target=_blank` blob so that it takes you to a new page. Also, what do you think about this metamask logo?

image

I'll leave it pre-approved, but feel free to choose whichever you like the most

**Review by albertov19 — APPROVED** [review]
LGTM! No faucet info for mobile tho?

**Review by albertov19 — APPROVED** [review]
LGTM!

**Review by albertov19 — APPROVED** [review]
Third time is the charm :)

**Pull request merged**
